# Use Python 3.9 slim image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy requirements file (optional)
COPY requirements.txt .
RUN pip install tqdm
RUN pip install --no-cache-dir -r requirements.txt
# Copy your Python scripts (optional)
# COPY . .

